# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev
    - libgsl0-dev
    - libcairo2-dev

env:
- STACK="stack --no-terminal --install-ghc test --haddock"

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# This line does all of the work: installs GHC if necessary, build the library,
# executables, and test suites, and runs the test suites. --no-terminal works
# around some quirks in Travis's terminal implementation.
matrix:
  include:
    - script: $STACK --flag inline-c:gsl-example
    - script:
        $STACK --stack-yaml stack-lts-12.14.yaml --flag inline-c:gsl-example
    # gtk2hs-buildtools is not present in nightly a bit of a pain to install,
    # skip it for now
    - script: $STACK --stack-yaml stack-nightly-2018-10-24.yaml
    - script: hlint .

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - .stack-work
  - inline-c/.stack-work/
  - inline-c-cpp/.stack-work/
  - sample-cabal-project/.stack-work/
